version: "3"

services:
  back:
    tty: true
    build:
      context: ./back
      dockerfile: ./docker/Dockerfile
    container_name: dev-net-vision-go
    volumes:
      - ./back:/go/src
    ports:
      - 8080:8080

  front:
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./front
      dockerfile: ./docker/Dockerfile
    container_name: dev-net-vision-node
    volumes:
      - ./front:/code
      - front_node_modules:/code/node_modules
    ports:
      - 5173:5173

volumes:
  front_node_modules: