name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check branch
      run: exit 1
      if: github.ref != 'refs/heads/release'
    
    - name: set branch
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    
    - uses: actions/checkout@v3
    - name: run build.sh
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Zip output
      run: |
        cd build
        zip -r release-windows windows/*
        zip -r release-linux linux/*
    
    - name: create tag
      run: |
        git tag ${{ github.event.inputs.version }} &{{ env.BRANCH_NAME }}
        git push origin ${{ github.event.inputs.version }}
    
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset - windows
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/release-windows.zip
        asset_name: NetVision-${{ github.event.inputs.version }}-win.zip
        asset_content_type: application/zip
        
    - name: Upload Release Asset - linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/release-linux.zip
        asset_name: NetVision-${{ github.event.inputs.version }}-linux.zip
        asset_content_type: application/zip
